-- EXAMPLE MIGRATION FILE — for a fake "library" app
-- Reference this while writing your own migration files.
-- Do NOT copy-paste — translate the patterns to Altus's schema.
--
-- REFERENCE DOCS (read these alongside this file):
--
-- PostgreSQL CREATE TABLE syntax
--   https://www.postgresql.org/docs/current/sql-createtable.html
--
-- PostgreSQL data types (UUID, TEXT, VARCHAR, INTEGER, DECIMAL, BOOLEAN, TIMESTAMP)
--   https://www.postgresql.org/docs/current/datatype.html
--
-- PostgreSQL ENUM types
--   https://www.postgresql.org/docs/current/datatype-enum.html
--
-- PostgreSQL CHECK constraints
--   https://www.postgresql.org/docs/current/ddl-constraints.html
--
-- gen_random_uuid() — built-in UUID generation (PostgreSQL 13+)
--   https://www.postgresql.org/docs/current/functions-uuid.html

-- ============================================================
-- PART 1: Create a custom ENUM type (if your table uses one)
-- ENUMs are database-level types. Create them before the table.
-- Use IF NOT EXISTS to make this safe to run more than once.
-- ============================================================

DO $$ BEGIN
  CREATE TYPE member_status AS ENUM ('active', 'suspended', 'expired');
EXCEPTION
  WHEN duplicate_object THEN NULL; -- silently skip if already exists
END $$;


-- ============================================================
-- PART 2: Create the table
-- ============================================================

CREATE TABLE IF NOT EXISTS library_members (

  -- UUID primary key, auto-generated by PostgreSQL
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- VARCHAR limits the max length. NOT NULL means the column is required.
  full_name VARCHAR(100) NOT NULL,

  -- UNIQUE means no two rows can have the same email
  email VARCHAR(255) UNIQUE NOT NULL,

  -- TEXT has no length limit. Nullable (no NOT NULL) means optional.
  notes TEXT,

  -- Using the ENUM type we created above
  status member_status NOT NULL DEFAULT 'active',

  -- DEFAULT NOW() means PostgreSQL fills this in automatically on INSERT
  joined_at TIMESTAMP NOT NULL DEFAULT NOW()

);


-- ============================================================
-- PART 3: Foreign key example (in a different table)
-- This table references library_members — so that table must
-- be created first (in an earlier numbered migration file).
-- ============================================================

CREATE TABLE IF NOT EXISTS borrowed_books (

  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- This column references the id column in library_members.
  -- If the referenced member is deleted, ON DELETE CASCADE
  -- automatically deletes their borrow records too.
  member_id UUID NOT NULL REFERENCES library_members(id) ON DELETE CASCADE,

  book_title VARCHAR(200) NOT NULL,

  borrowed_at TIMESTAMP NOT NULL DEFAULT NOW(),

  -- Nullable: no return date until the book is actually returned
  returned_at TIMESTAMP

);


-- ============================================================
-- PART 4: CHECK constraint example
-- Enforces a business rule at the database level.
-- This is stronger than application-level validation —
-- even if your code has a bug, the database will reject bad data.
-- ============================================================

CREATE TABLE IF NOT EXISTS staff (

  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,

  -- Staff must have at least one contact method.
  -- The CHECK constraint enforces this — you cannot insert
  -- a row where BOTH phone and email are NULL.
  phone VARCHAR(20),
  email VARCHAR(255),

  CONSTRAINT staff_must_have_contact
    CHECK (phone IS NOT NULL OR email IS NOT NULL)

);


-- ============================================================
-- PART 5: Composite primary key example
-- Used when the combination of two columns is what's unique —
-- not either column on its own.
-- Example: one member can borrow many books,
--          one book can be borrowed by many members,
--          but one member cannot borrow the same book twice at once.
-- ============================================================

CREATE TABLE IF NOT EXISTS member_reading_list (

  member_id UUID NOT NULL REFERENCES library_members(id) ON DELETE CASCADE,
  book_id   UUID NOT NULL,
  added_at  TIMESTAMP NOT NULL DEFAULT NOW(),

  -- The PRIMARY KEY is the COMBINATION of both columns
  PRIMARY KEY (member_id, book_id)

);
