name: CI

on: # Trigger the workflow on push or pull request to the main branch
  push:
  pull_request:
    branches: ['main', 'dev']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: 'npm ci'
      - run: 'npm run lint'

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: 'npm ci'
      - run: 'npm run build'

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: altus-backend
          HEROKU_EMAIL: patrick.macabulos@gmail.com
        run: |
          cat > ~/.netrc <<EOF
          machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          EOF
          git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
          git push heroku main
